# Generated by Django 2.2.3 on 2019-10-05 10:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', django.contrib.postgres.fields.jsonb.JSONField()),
                ('platform', django.contrib.postgres.fields.jsonb.JSONField()),
                ('mongo', django.contrib.postgres.fields.jsonb.JSONField()),
                ('postgres', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when statistic was created.', verbose_name='date created')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
