# Generated by Django 2.2.3 on 2019-10-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phasma_device',
            field=models.ForeignKey(help_text='Phasma device used during measurement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='devices.PhasmaDevice'),
        ),
    ]
