# Generated by Django 2.2.3 on 2019-10-21 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhasmaDevice',
            fields=[
                ('mac', models.CharField(help_text='MAC (Media Access Control) address of phasma device.', max_length=127, primary_key=True, serialize=False, verbose_name='media access control address')),
                ('name', models.CharField(help_text='Name of phasma device.', max_length=127, verbose_name='name')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when phasma device was added.', verbose_name='date added')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date when phasma device was updated.', verbose_name='date updated')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
